name: example
on:
  schedule:
    - cron: '*/5 * * * *' # 每 5 分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 210513
          schedule-id: 100034
          seat-id: 7_159
          slack-incoming-webhook-url: ${{ secrets.MELON }}
          message: '달려달려~'
